### ISSUE TITLE
USER STORY: Create databse relationships

### ISSUE THREAD

**Issue by Njorogetracy** [Njorogetracy/managey_drf#13]
As a developer, I need to define the relationships between the models in the database.

**Acceptance Criteria**
All models are working with the defined relationships and all models related to other app models are linked 

**Tasks**

- [x] Create Database models for apps
- [x] set relationships between models
- [x] make migrations using the _python3 manage.py makemigrations_ command
- [x] migrate the new models to keep the database updated using the _python3 manage.py migrate_ command
