### ISSUE TITLE
USER STORY: Set up GitHub repository

### ISSUE THREAD

**Issue by Njorogetracy** [Njorogetracy/managey_drf#14]
As a Site Developer, I need to set-up two repositories on GitHub, Frontend and Backend platform to be able to have control over versions of project.

**Accceptance Criteria**
Working GitHub repository

**Tasks**:

- [x] Create Frontend repository for the project
- [x] Create Backend repository for project
- [x] Create project workflow on the backend repository
- [x] Create Epics
- [x] Create User stories
- [x] Create labels for importance
