### ISSUE TITLE
USER STORY: Create Django app

### ISSUE THREAD

**Issue by Njorogetracy** [Njorogetracy/managey_drf#15]
As a Site Developer, I need to set all dependencies, correctly set settings.py and create working app in local environment.

**Tasks**:

- [x] Install Django using pip3 install ‘django<4’
- [x] Create Project using django-admin startproject 'projectname'
- [x] Install Cloudinary Storage:  pip3 install cloudinary django-cloudinary-storage
- [x] Install Pillow: pip3 install Pillow==8.2.0
- [x] Add all installed apps to settings.py and create storage
