### ISSUE TITLE
USER STORY: Deploy to heroku

### ISSUE THREAD

**Issue by Njorogetracy** [Njorogetracy/managey_drf#16]
As a Site Developer I need to create a working Heroku deployement for the intial project

**Acceptance Criteria** 

Working Heroku Deployment, when first deployed site is accessed, it gives hint of correctly installed Django App (DEBUG = True). Create if statement in settings.py for DEBUG = False for final deployment.

**Tasks**:

- [x] Create Heroku App
- [x]  Link with GitHub
- [x] Set up Vars
